before_script:
  - npm install -g bower
  - bower install -f
sudo: false
language: node_js
node_js:
- '0.11'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c7221c310d73040384ce
    on_success: always
    on_failure: always
    on_start: false
